---
ansible_user: kamil
bind_domains:
  - name: lan.mycka.net
    network: "172.30"
    serial: 2025110901
    nameserver_ip: 172.30.20.10
    hosts:
      - name: dns
        type: A
        ip: 172.30.20.10
      - name: router
        type: A
        ip: 172.30.100.1
      - name: switch
        type: A
        ip: 172.30.100.2
      - name: nextcloud
        type: A
        ip: 172.30.20.11
      - name: librenms
        type: A
        ip: 172.30.20.12
      - name: smokeping
        type: A
        ip: 172.30.20.13
      - name: nas
        type: A
        ip: 172.30.20.14
      - name: jellyfin
        type: A
        ip: 172.30.20.15
      - name: cups
        type: A
        ip: 172.30.20.16
      - name: rpi1
        type: A
        ip: 172.30.40.11
      - name: rpi2
        type: A
        ip: 172.30.40.12
      - name: rpi3
        type: A
        ip: 172.30.40.13
      - name: rpi4
        type: A
        ip: 172.30.40.14
      - name: pve1
        type: A
        ip: 172.30.100.101
      - name: pve2
        type: A
        ip: 172.30.100.102
      - name: master01
        type: A
        ip: 172.30.40.15
      - name: master02
        type: A
        ip: 172.30.40.16
      - name: master03
        type: A
        ip: 172.30.40.11
      - name: worker01
        type: A
        ip: 172.30.40.17
      - name: worker02
        type: A
        ip: 172.30.40.18
      - name: worker03
        type: A
        ip: 172.30.40.12
      - name: worker04
        type: A
        ip: 172.30.40.13
      - name: worker05
        type: A
        ip: 172.30.40.14