---
ansible_user: kamil
bind_domains:
  - name: lan.mycka.net
    network: "172.30"
    serial: 2025110901
    nameserver_ip: 172.30.20.10
    hosts:
      - name: dns
        type: A
        ip: 172.30.20.10
      - name: router
        type: A
        ip: 172.30.100.1
      - name: crs326
        type: A
        ip: 172.30.100.2
      - name: nextcloud
        type: A
        ip: 172.30.20.11
      - name: librenms
        type: A
        ip: 172.30.20.12
      - name: smokeping
        type: A
        ip: 172.30.20.13
      - name: nas
        type: A
        ip: 172.30.20.14
